### PR TITLE
Add OpenDNS/Cisco Umbrella DNS provider

### PR DESCRIPTION
**Pull request by da2x**

### CODE REVIEW

**Comment by RangerMauve** [comment]
cc @pfrazee can this get merged in? (alternately, could I get NPM/Repo access to merge stuff in in the future?)

**Comment by pfrazee** [comment]
Hey sorry this fell through the cracks, what's the upside to adding opendns? Just more redundancy?

It's possible to pass a custom provider from the outside.

**Comment by da2x** [comment]
> Hey sorry this fell through the cracks, what's the upside to adding opendns? Just more redundancy?

More redundancy, yes. It makes Dat less reliant on a single service provider.

**Comment by pfrazee** [comment]
Aight sgtm. Published `4.1.2`

**Pull request merged**
